# Generated by Django 4.1.5 on 2023-01-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycommerce', '0004_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='commentaire',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='nom',
            new_name='user_name',
        ),
    ]
