# Generated by Django 4.1.5 on 2023-01-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycommerce', '0005_rename_commentaire_commentaire_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='message',
            new_name='commentaire',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='date_created',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='user_name',
            new_name='nom',
        ),
    ]
