# Generated by Django 4.1.5 on 2023-01-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycommerce', '0007_comment_delete_commentaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
