# Generated by Django 4.1.5 on 2023-01-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycommerce', '0010_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
