# Generated by Django 4.1.5 on 2023-02-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycommerce', '0016_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('message', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
