# Generated by Django 4.1.5 on 2023-02-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easycommerce', '0017_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.TextField(),
        ),
    ]
