# Generated by Django 4.1.5 on 2023-02-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycommerce', '0018_alter_reply_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
