# Generated by Django 4.1.6 on 2023-02-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycommerce', '0022_alter_reply_date_add'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
