# Generated by Django 4.1.6 on 2023-02-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycommerce', '0031_remove_cart_date_added_remove_cart_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
